theme: jekyll-theme-architect
title: François HU
description: This webpage is about me, my research and my teaching
google_analytics: UA-163147530-1
logo: images/logo.png
photo: images/logo.png
linkedin: https://www.linkedin.com/in/fran%C3%A7ois-hu-9b6295136/?originalSubdomain=fr
