theme: jekyll-theme-architect
title: François HU
description: About Research, Teaching and Gaming
google_analytics: UA-163147530-1
tags: webpage, homepage, page perso, active learning, machine learning, deep learning, reinforcement learning
permalink: https://www.linkedin.com/in/fran%C3%A7ois-hu-9b6295136/
categories: Machine Learning
