theme: jekyll-theme-architect
title: François HU
description: About Research, Teaching and Gaming
google_analytics: UA-163147530-1
tags: webpage, homepage, page perso, active learning, machine learning, deep learning, reinforcement learning
permalink:
categories: Machine Learning
